Add coupon generator and option to orders to add a coupon to each order
woocommerce/wc-smooth-generator pull request #71
Opened 2021-12-03 19:31 UTC by louwie17

Fixes #68 

### Description

Added a Coupon generator with a min and max option for the `int_random` function.

I also added a `coupon` option to the order generator CLI command, which if set, it will auto generate a coupon for each order.

### Testing instructions

- Run `wp wc generate coupons 10 --min=10 --max=40`
- Go to **Marketing > Coupons** and see if there are 10 new coupons (no duplicates)
- Run `wp wc generate orders 10 --status=completed --coupons=true`
- Run `wp action-scheduler run`
- Go to **Analytics > Coupons** and see if there are 10 coupons listed with an order each

2021-12-06 17:16 UTC, rrennick commented
@louwie17 Thanks for the PR. Could you add a change log entry to your PR description? There is also a merge conflict that needs to be addressed.

2021-12-06 17:38 UTC, louwie17 commented
> @louwie17 Thanks for the PR. Could you add a change log entry to your PR description? There is also a merge conflict that needs to be addressed.

Hi @rrennick, I added the change log entry and rebased the branch.

2021-12-07 17:48 UTC, rrennick requested changes
@louwie17 This tested great for me. I only had the two minor issues that need to be looked at. Once those are fixed I'll be able to merge this.

2021-12-07 17:48 UTC, rrennick commented on includes/Generator/Order.php
> +		$include_coupon = ! empty( $assoc_args['status'] );
Should this be `$assoc_args['coupons']`?

2021-12-07 17:48 UTC, rrennick commented on includes/Generator/Coupon.php
> +		self::init_faker();
t doesn't look like the faker is used in this function.

2021-12-10 00:16 UTC, louwie17 commented
> @louwie17 This tested great for me. I only had the two minor issues that need to be looked at. Once those are fixed I'll be able to merge this.

Thanks for the review @rrennick, great catch on both of those, I have pushed up those changes in this commit: https://github.com/woocommerce/wc-smooth-generator/pull/71/commits/1d497d44267f79b714d516b1c64e87906eec5389

2021-12-13 22:53 UTC, rrennick approved these changes
@louwie17 Thanks for the help.

2021-12-13 22:53 UTC, merged